directories:
  output: dist
  buildResources: assets
appId: com.starzone.client
productName: StarZone Client
extraResources:
  - filter:
      - ./flash/**
      - ./assets/css/**
      - ./assets/images/**
mac:
  category: public.app-category.games
linux:
  target:
    - AppImage
  category: Game
files: []
electronVersion: 14.2.9
